# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Verify Plugin

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - develop
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --no-daemon --console=plain -q)"
          which md5sum > /dev/null || alias md5sum=md5
          IDE_VERSIONS="$(echo "$PROPERTIES" | grep "^pluginVerifierIdeVersions:" | md5sum)"
          echo "::set-output name=ideVersions::$IDE_VERSIONS"
          echo "::set-output name=pluginVerifierHomeDir::~/.pluginVerifier"
          touch results-${GITHUB_SHA}.txt
          echo "output file results-${GITHUB_SHA}.txt"

      - name: Setup Plugin Verifier IDEs Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: ${{ runner.os }}-plugin-verifier-${{ steps.properties.outputs.ideVersions }}

      - name: Results file header
        run: |
          echo "Run date: `date`" >> results-${GITHUB_SHA}.txt
          echo "on commit \"${{ env.COMMIT_MSG }}\" (${GITHUB_SHA})" >> results-${GITHUB_SHA}.txt
          echo >> results-${GITHUB_SHA}.txt

      - name: Gradle check
        run: |
          cmd="./gradlew check --console=plain"
          echo $cmd >> results-${GITHUB_SHA}.txt  
          eval $cmd | tee -a results-${GITHUB_SHA}.txt
          echo '============================================' >> results-${GITHUB_SHA}.txt  
          echo >> results-${GITHUB_SHA}.txt

      - name: Verify Plugin
        run: |
          cmd="./gradlew verifyPlugin --console=plain"
          echo $cmd >> results-${GITHUB_SHA}.txt  
          eval $cmd | tee -a results-${GITHUB_SHA}.txt
          echo '============================================' >> results-${GITHUB_SHA}.txt
          echo >> results-${GITHUB_SHA}.txt

      - name: Verify IntelliJ Compatibility
        id: verify
        run: |
          cmd="./gradlew runPluginVerifier --console=plain -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}"
          echo $cmd >> results-${GITHUB_SHA}.txt  
          eval $cmd | tee -a results-${GITHUB_SHA}.txt
          echo '============================================' >> results-${GITHUB_SHA}.txt
          echo >> results-${GITHUB_SHA}.txt
          echo "::set-output name=results-file-name::results-${GITHUB_SHA}.txt"
